### ISSUE TITLE
Status of PGQL

### ISSUE THREAD

**Issue by manishrjain** [oracle/pgql-lang#19]
Hey, author of Dgraph here.

Is this language being or going to be used by some graph product by Oracle? Is Neo4j going to support this? Are there other graph vendors who are bought into this QL?

I'm curious because we need a query language which can fix the limitations of GraphQL. And we're wondering choosing between Open Cypher and this.

**Comment by oskar-van-rest** [comment]
Hi Manish,

> Is this language being or going to be used by some graph product by Oracle?

PGQL is implemented in Oracle Labs's Parallel Graph AnalytiX (PGX): http://www.oracle.com/technetwork/oracle-labs/parallel-graph-analytix/overview/index.html

And PGX in its turn is part of two products at Oracle:

 - Oracle Spatial and Graph: http://www.oracle.com/technetwork/database/options/spatialandgraph/overview/index.html
 - Oracle Big Data Spatial and Graph: http://www.oracle.com/technetwork/database/database-technologies/bigdata-spatialandgraph/overview/index.html

> Is Neo4j going to support this?

Very unlikely I think.
Neo4j and Oracle are working together though on the G-CORE effort (http://wiki.ldbcouncil.org/display/TUC/Tenth+TUC+Meeting%2C+TU+Munich+at+VLDB2017?preview=/81920005/87588865/g-core.pdf) and more recently on SQL-extension for graphs, but it is unclear how those projects will affect PGQL or Cypher.

> Are there other graph vendors who are bought into this QL?

Not right now AFAIK.

Let me know if you have other questions. Also feel free to use our PGQL parser (this repository).

**Comment by manishrjain** [comment]
Thanks for your reply.
